services:
  csharp-api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: csharp-api
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"
    networks:
      - backend
    env_file:
      - .env
    environment:
      - METRICS_SQLITE_PATH=/app/config/config.db
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./src/Api/config:/app/config
      - ./src/Api/logs:/app/logs
    depends_on:
      - sqlite

  csharp-runner:
    build:
      context: .
      dockerfile: src/Runner/Dockerfile
    container_name: csharp-runner
    restart: on-failure
    init: true
    networks:
      - backend
    env_file:
      - .env
    environment:
      - METRICS_SQLITE_PATH=/app/config/config.db
      - DOTNET_ENVIRONMENT=Production
    volumes:
      - ./src/Api/config:/app/config
      - ./src/Api/logs:/app/logs
    depends_on:
      - csharp-api

  sqlite:
    image: busybox
    container_name: sqlite
    restart: no
    networks:
      - backend
    volumes:
      - ./src/Api/config:/data
    command: "tail -f /dev/null"

networks:
  backend:
    driver: bridge
